config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'records#index'

  resources :records  do
      resources :comments, only: :create
  end

  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
    
  





  resource :user, except: [:new, :create, :destroy]





end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :training_site
  belongs_to :training_event
  belongs_to :times
  belongs_to :set_count

  validates :days, presence: true
  validates :weight, presence: true
  validates :image, presence: true

  validates :training_site_id, numericality: { other_than: 1, message: 'を選択してください' }
  validates :training_event_id, numericality: { other_than: 1, message: 'を選択してください' }
  validates :times_id, numericality: { other_than: 1, message: 'を選択してください' }
  validates :set_count_id, numericality: { other_than: 1, message: 'を選択してください' }
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_record, only: [:edit, :show, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :destroy]

  def index
    @record = Record.find_by(params[:id])
    @records = Record.all
    @records = Record.order('created_at DESC')
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)

    if @record.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @record.comments.includes(:user)
  end

  def edit
    return unless @record.user != current_user

    redirect_to record_path, alert: '不正なアクセスです。'
  end

  def update
    if @record.update(record_params)
      redirect_to record_path
    else
      render :edit
    end
  end

  def destroy
    if @record.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def record_params
    params.require(:record).permit(:days, :training_site_id, :training_event_id, :times_id, :set_count_id, :weight, :thoughts,
                                   :image).merge(user_id: current_user.id)
  end

  def set_record
    @record = Record.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @record.user
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/edit.html.erb
   
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">

  <h1>本日のトレーニングを記録<i class="fa-solid fa-pen"></i></h1>
  <%=form_with model: @record, local: true do |f|%>


<div class="form-group">
      <%= f.label :days, "日付" %><br />
      <%= f.date_field  :days, class: "form-control"%>
     </div>
   
    <div class="form-group">
    <%= f.label :training_site_id, "トレーニング部位" %><br />
    <%= f.collection_select :training_site_id, TrainingSite.all, :id, :name, {}, class: "form-control" %>
    </div>

     <div class="form-group">
    <%= f.label :training_event_id , "トレーニング種目" %><br />
    <%= f.collection_select :training_event_id ,TrainingEvent.all, :id, :name, {}, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :weight, "重量 or 消費カロリー" %><br />
    <%= f.text_field :weight, id:"record_weight",placeholder:"キログラム or カロリー", autofocus: true, autocomplete: "height", class: "form-control"  %>
     </div>


     <div class="form-group">
    <%= f.label :times_id , "回数・有酸素時間" %><br />
    <%= f.collection_select :times_id ,Times.all, :id, :name, {}, class: "form-control"  %>
    </div>

    
    <div class="form-group">
    <%= f.label :set_count_id, "セット数" %><br />
    <%= f.collection_select :set_count_id,SetCount.all, :id, :name, {}, class: "form-control"  %>
    </div>

  <div class="form-group">
     <%= f.label :thoughts , "感想・備考欄" %><br />
     <%= f.text_area :thoughts, class:"text", id:"record_thoughts", placeholder:"トレーニングの感想・メモ" ,rows:"7" ,maxlength:"1000" ,class: "form-control"%>
  </div>

   <div class="form-group">
     <%= f.label :thoughts , "画像を添付" %><br />
     <%= f.file_field :image, id:"record-image", class: "form-control" %>
   </div>


     <div>  
        <div class="d-grid gap-2 col-6 mx-auto">
          <%= f.submit "記録を編集する", class: "btn btn-primary" %>
           <%=link_to 'もどる', record_path, class:"btn btn-primary" %>
        </div>
      </div>
    </div>   
     
 <% end %>
</div>
</div>
</div>

app/views/records/index.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/69783dde2e.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
   
<main>

  <section class="py-5 text-center container">
  
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">You’re awesome, you know?</h1>
        <p class="lead text-muted">さあ、本日もトレーニング内容を記録しましょう</p>
        
    <%# トレーニング記録 %>
     <% if user_signed_in? %>
        <%= link_to( new_record_path) do %>
          <span class="btn btn-primary my-2 fa-bounce">本日のトレーニングを追加</span>
        <% end %>
      <% else %>
        <p>
        <%= link_to( new_user_session_path) do %>
          <button type="button" class="btn btn-outline-primary btn-lg fa-beat-fade">login</button>
           <% end %>
        <%= link_to( new_user_registration_path) do %>
          <button type="button" class="btn btn-outline-success btn-lg fa-beat-fade ">sign up</button>
        <% end %>
        </p>
      <% end %>


      </div>
    </div>
  </section>

 <% @records.each do |record| %>
  <div class="album py-5 bg-light ">
    <div class="container">

      <div class="row row-cols- row-cols-sm-2 g-2 justify-content-center ">

        <div class="col">
          <div class="card shadow-sm">
      
  
         <%= image_tag record.image, class: "item-img" if record.image.attached? %>

        <div>
         <button type="button" class="btn btn-secondary btn-sm">投稿者 <%=record.user.nickname%></button>
        </div>
        
        

 <div class="card-body">
  <p><div>
    <div class = "record-days" >
      <p>day: <%= record.days %>日</p>
    </div>
    <div>
      <p>トレーニング部位: <%= record.training_site.name %></p>
    </div>
    <div>
      <p>トレーニング種目: <%= record.training_event.name %></p>
    </div>
    <div >
      <p>メモ: <%= record.thoughts %></p>
    </div>
  </div></p>
          <% if user_signed_in? %>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                 <%= link_to( record_path(record.id), method: :get ) do %>
                  <button type="button" class="btn btn-outline-primary"> <%='view more' %></button>
                 <% end %>
                </div>
          <% end %>
                <div id="favorites_buttons_<%= @record.id %>">
                  <%# ここをいいねできるようにしたい %>
                  <%= render partial: "favorites/favorite", record: record %>
                </div>
                  <%# ここをいいねできるようにしたい %>
              </div>
            </div>
          </div>
        </div>
        
        
        
      </div>
    </div>
  </div>
<% end %>

</main>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/records/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">

  <h1><i class="fa-solid fa-pen  fa-beat"></i>本日のトレーニングを記録<i class="fa-solid fa-pen  fa-beat"></i></h1>
  <%=form_with model: @record, url: records_path, local: true do |f|%>



     <div class="form-group">
      <%= f.label :days, "日付" %><br />
      <%= f.date_field  :days, class: "form-control"%>
     </div>
   
    <div class="form-group">
    <%= f.label :training_site_id, "トレーニング部位" %><br />
    <%= f.collection_select :training_site_id, TrainingSite.all, :id, :name, {}, class: "form-control" %>
    </div>

     <div class="form-group">
    <%= f.label :training_event_id , "トレーニング種目" %><br />
    <%= f.collection_select :training_event_id ,TrainingEvent.all, :id, :name, {}, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :weight, "重量 or 消費カロリー" %><br />
    <%= f.text_field :weight, id:"record_weight",placeholder:"キログラム or カロリー", autofocus: true, autocomplete: "height", class: "form-control"  %>
     </div>


     <div class="form-group">
    <%= f.label :times_id , "回数・有酸素時間" %><br />
    <%= f.collection_select :times_id ,Times.all, :id, :name, {}, class: "form-control"  %>
    </div>

    
    <div class="form-group">
    <%= f.label :set_count_id, "セット数" %><br />
    <%= f.collection_select :set_count_id,SetCount.all, :id, :name, {}, class: "form-control"  %>
    </div>

  <div class="form-group">
     <%= f.label :thoughts , "感想・備考欄" %><br />
     <%= f.text_area :thoughts, class:"text", id:"record_thoughts", placeholder:"トレーニングの感想・メモ" ,rows:"7" ,maxlength:"1000" ,class: "form-control"%>
  </div>

   <div class="form-group">
     <%= f.label :thoughts , "画像を添付" %><br />
     <%= f.file_field :image, id:"record-image", class: "form-control" %>
   </div>

      <div>  
        <div class="d-grid gap-2 col-6 mx-auto">
          <%= f.submit "記録する", class: "btn btn-dark" %>
        </div>
      </div>
    </div>
  
 <% end %>
</div>
</div>
</div>

app/views/records/show.html.erb
 
  <div class="album py-5 bg-light ">
  
    <div class="container">

      <div class="row row-cols- row-cols-sm-2 g-2 justify-content-center ">

        <div class="col">
          <div class="card shadow-sm">

             <%= image_tag @record.image %>

                <div class="card-body">
                  <p>
                    <div class = "record-days" >
                       <p>day: <%= @record.days %>日</p>
                    </div>
                    <div>
                       <p>トレーニング部位: <%= @record.training_site.name %></p>
                    </div>
                    <div>
                      <p>トレーニング種目: <%= @record.training_event.name %></p>
                    </div>
                     <div >
                       <p>重量 or 消費カロリー: <%= @record.weight %></p>
                    </div>
                     <div >
                       <p>回数・有酸素時間: <%= @record.times.name %></p>
                    </div>
                     <div >
                       <p>セット数: <%= @record.set_count.name %></p>
                    </div>
                    <div >
                       <p>感想・メモ: <%= @record.thoughts %></p>
                    </div>
                  </p>   
          <% if current_user.liked_by?(@record.id) %>
            <td>
                <%= link_to  destroy_favorite_path(@record), method: :DELETE, remote: true do %> 
                  <i class="fa-solid fa-thumbs-up fa-beat"></i>
                <%= @record.favorites.count %>
              <% end %>
            </td>
          <% else %>
            <td>
               <%= link_to create_favorite_path(@record), method: :POST, remote: true do %> 
                 <i class="fa-solid fa-thumbs-up fa-beat"></i>
                <%= @record.favorites.count %>
               <% end %>
            </td>
          <% end %>
                <% if @record.user == current_user %>
                   <p>
                    <%= link_to( edit_record_path) do %>
                  <button type="button" class="btn btn-warning">記録を編集</button>
                    <% end %>

                     <%= link_to record_path, method: :delete  do %>
                    <button type="button" class="btn btn-success">記録を削除</button>
                    <% end %>
                    </p>
                <% end %>
                         

          
          </div>                  
        </div>
      </div>
            <div class="container">
             <div class="row row-cols- row-cols-sm-2 g-2 justify-content-center ">
              <div class="col">
               <div class="card shadow-sm">
                <div class="card-body">
                  <% if user_signed_in? %>
                    <%= form_with(model: [@record, @comment], local: true) do |form| %>
                        <div class="form-group">
                          <%= form.text_area :text, placeholder: "コメントする", rows: "2" ,class: "form-control"%>
                        </div>
                         <div class="d-grid gap-2 col-6 mx-auto">
                          <%= form.submit "SEND", class: "btn btn-outline-secondary" %>
                        </div>
                    <% end %>
                  <% else %>
                    <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
                  <% end %>
                  <div class="comments">
                    <h4>＜コメント一覧＞</h4>
                    <% @comments.each do |comment| %>
                      <p>
                        <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
                        <%= comment.text %>
                      </p>
                    <% end %>
                 </div>
                </div>
               </div>
              </div>
             </div>
            </div>
    </div>
   </div>
                 
            